# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  #vmImage: ubuntu-latest
  name: default

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8' 
    jdkArchitectureOption: 'x64' # Options: x64, x86
    jdkSourceOption: 'LocalDirectory' # Options: AzureStorage, LocalDirectory
    jdkFile: '/home/akhil/openlogic-openjdk-8u292-b10-linux-x64.tar.gz'
    jdkDestinationDirectory: '/home/akhil/builds/binaries/externals'
    cleanDestinationDirectory: true
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
